### PR TITLE
Configure project for deployment to Maven Central

### LINKED ISSUE #8: Upload to Maven Central
It would be very helpful to have this library mirrored on maven central. With it being open source, Sonatype will even host it for free!

### PR DESCRIPTION
**Pull request by MariusVolkhart**
- Add configuration files
- Add release steps in REALESING.md
- Remove unused files

Works to resolve #8

### CODE REVIEW

**Comment by blurkidi** [comment]
I have to admit that I'm not a Maven user myself. I don't think that this changes should be in the main branch though. I could create a 'maven' branch if you want, and I will merge it on each release. The other option is that you maintain a fork with this changes.

Also, are the proguard files required?

**Comment by intrications** [comment]
This would be great. Looking through the commit, it looks like this will create an "aar" file so this would be used with Gradle and Android Studio (and possibly with Maven - can aar files be used in Maven yet?).

However, I do understand that it may be hard for @blurkidi to maintain if he is not using dependency management.

**Comment by MariusVolkhart** [comment]
I gave this some more thought, and came up with a few points for consideration.
1. As @blurkidi suggested, I could run a fork of this repo. The downside to this is that I can't deploy to Maven Central under this library's package, since I don't own the domain. So I'd actually need to rename everything to `com.volkhart.holoaccent`. Additionally, it might confuse other contributors as to which repository is the most up-to-date & such. Note that this is not a good solution.
2. We could "host" a maven repo on github, as seen [here](https://github.com/novoda/public-mvn-repo). This would certainly dirty up the repository, and also the repository would grow tremendously over time. This is a bad solution.

Thoughts?

@blurkidi the proguard files are not required. They get added by ADT & Android Studio, but aren't being used. In fact, everything in them was commented out, and the build files are not set up to use them.

@intrications yes, aars can be used w/ maven, though I have no experience w/ it - check out the [android-maven-plugin](https://code.google.com/p/maven-android-plugin/). I meant gradle, as you concluded.

**Comment by blurkidi** [comment]
After some (a lot) of reading, I think that it is a good idea to include this commit in the main branch. I already created a sonatype account and I tested pushing the artifacts. It works with a few changes: I had to add the following to the main build.gradle file:

```
allprojects {
    version = VERSION_NAME
    group = GROUP

    repositories {
        mavenCentral()
    }
}
```

The next release will be synced to maven central. Thank you very much for the collaboration.

**Pull request closed without merging**
