### PR TITLE
scaled down overscroll edge/glow resource to reduce memory usage

### PR DESCRIPTION
**Pull request by mariotaku**
Recently I received many bug reports caused by OOM errors, stack traces shows It's very easy to reach heap size when using large overscroll glow/edge, so I tried to scale it down to 33% of original version, I found it improves a lot and visually no difference. Please consider to use smaller overscroll edge/glow bitmap, thank you :)

### CODE REVIEW

**Comment by blurkidi** [comment]
That is a serious issue, I will analyse the lib and how we manage the overscroll drawables, how memory behaves... You could maybe share these stack traces or some code snippets that may help.

In any case, something tells me that the problem is not caused by the overscroll drawables, that is just a symptom of something bigger, and for sure making the drawables smaller is not the solution. And it might be an implementation issue too (like a context leak) so I will need your help on this. Do you manage to reproduce it yourself? If so, how?

**Comment by mariotaku** [comment]
Here's stack trace, a user sent me 8 emails, and all of them are caused by OOM during decode overscroll glow.
I checked my mail box, recently there are 16 of 20 emails about this error. Seems OOM usually happens on low memory devices. I believe using smaller overscroll drawable could prevent most of them.

```
Report date: Wed Apr 16 08:16:46 CDT 2014
Android version: 4.4.2
API version: 19
App version name: 0.2.9.12
App version code: 94
Configuration: {0 1.0 310mcc260mnc en_US ldltr sw360dp w360dp h615dp 480dpi nrml long port finger -keyb/v/h -nav/h s.30}
Stack trace:
java.lang.OutOfMemoryError
at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:677)
at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:507)
at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:872)
at android.content.res.Resources.loadDrawable(Resources.java:3024)
at android.content.res.Resources.getDrawable(Resources.java:1586)
at com.negusoft.holoaccent.AccentResources.access$201(AccentResources.java:62)
at com.negusoft.holoaccent.AccentResources$OverScrollInterceptor.getGlowDrawable(AccentResources.java:280)
at com.negusoft.holoaccent.AccentResources$OverScrollInterceptor.getDrawable(AccentResources.java:269)
at com.negusoft.holoaccent.AccentResources.getDrawable(AccentResources.java:175)
at org.mariotaku.twidere.content.res.TwidereAccentResources.getDrawable(TwidereAccentResources.java:30)
at android.widget.EdgeEffect.<init>(EdgeEffect.java:150)
at android.widget.AbsListView.setOverScrollMode(AbsListView.java:1182)
at android.view.View.<init>(View.java:3579)
at android.view.View.<init>(View.java:3645)
at android.view.ViewGroup.<init>(ViewGroup.java:480)
at android.widget.AdapterView.<init>(AdapterView.java:241)
at android.widget.AbsListView.<init>(AbsListView.java:1060)
at android.widget.ListView.<init>(ListView.java:152)
at org.mariotaku.refreshnow.widget.RefreshNowListView.<init>(RefreshNowListView.java:24)
at org.mariotaku.refreshnow.widget.RefreshNowListView.<init>(RefreshNowListView.java:20)
at org.mariotaku.refreshnow.widget.RefreshNowListView.<init>(RefreshNowListView.java:16)
at org.mariotaku.twidere.fragment.support.BasePullToRefreshListFragment.onCreateView(BasePullToRefreshListFragment.java:113)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:927)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:570)
at org.mariotaku.twidere.activity.support.BaseSupportActivity.onStart(BaseSupportActivity.java:132)
at org.mariotaku.twidere.activity.support.LinkHandlerActivity.onStart(LinkHandlerActivity.java:148)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1189)
at android.app.Activity.performStart(Activity.java:5436)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
at android.app.ActivityThread.access$900(ActivityThread.java:161)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5356)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
at dalvik.system.NativeStart.main(Native Method)

```

**Comment by blurkidi** [comment]
Ok, I found out that the overscroll drawables are instantiated several times, once per each view that is using it. I cache the drawable now, which is a nice improvement. It is on the 'dev' branch if you want to have a look.

But I also found out that it is instantiated several times even if you don't use HoloAccent, so it is the normal behavior. And it is not normal that you run out of memory for a few drawables, even in low end devices. Are you sure you are not leaking the context, it is a common cause for this kind of errors. Can you reproduce it? Does it happen after a while? After doing so many rotations? You can maybe monitor your app to see how the memory footprint behaves.

**Comment by mariotaku** [comment]
Thanks! I'll try to trace memory usage in my app also. Do you have any advice for tracing ram usage?

**Comment by blurkidi** [comment]
There is the "Android Device Monitor" which is included in the SDK, I start it straight from Android Studio. There, you have the "heap" tab that might give you a clue about what is going on.

**Comment by mariotaku** [comment]
I used "dump heap" and analysing it in Eclipse MAT, and see Resources used RAM most.

**Comment by blurkidi** [comment]
Tha's it, I suggest you use that to see how memory behaves over time. Sepcially after rotations and configuration changes.
It is just a guess, but it is common to keep a reference to the context, which is an error. When you rotate the string the activity is destroyed and a new one create, so keeping a reference to the old one avoids the old resources being removed. So after each screen rotation the memory will increase until it crashes.
It could be nice to either confirm or discard that this is what is happening.

**Pull request closed without merging**
